version: "3"

services:
  mariadb:
    restart: always
    image: mariadb:10.10-jammy
    environment:
      MARIADB_DATABASE: $DB_DATABASE
      MARIADB_USER: $DB_USERNAME
      MARIADB_PASSWORD: $DB_PASSWORD
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - ./mariadb:/var/lib/mysql

  server:
    restart: always
    depends_on:
      - mariadb
    build:
      context: docker/server
      dockerfile: Dockerfile
    user: user
    tty: true
    stdin_open: true
    working_dir: /home/user
    volumes:
      - .:/home/user

  nginx:
    restart: always
    depends_on:
      - php
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - .:/home/user
